name: ALGOHUB CI


on:
  pull_request:
    branches:
      - develop
  workflow_call:
    inputs:
      run_tests:
        required: true
        type: boolean

permissions:
  contents: read


jobs:

  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: JDK 21 Setup
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: 'algohub'
          mysql root password: ${{ secrets.DB_PASSWORD }}

      - name: Create mysql.yml
        run: echo "${{ secrets.MYSQL_YML_TEST }}" | base64 --decode > src/main/resources/mysql.yml

      - name: Create aws.yml
        run: echo "${{ secrets.AWS_YML }}" | base64 --decode > src/main/resources/aws.yml

      - name: Create jwt.yml
        run: echo "${{ secrets.JWT_YML }}" | base64 --decode > src/main/resources/jwt.yml

      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Test YML
        run: ls -l src/main/resources

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: test