name: ALGOHUB CI


on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: JDK 21 Setup
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create mysql.yml
        run: echo "${{ secrets.MYSQL_YML }}" | base64 --decode > src/main/resources/mysql.yml

      - name: Create aws.yml
        run: echo "${{ secrets.AWS_YML }}" | base64 --decode > src/main/resources/aws.yml

      - name: Create jwt.yml
        run: echo "${{ secrets.JWT_YML }}" | base64 --decode > src/main/resources/jwt.yml

      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Test YML
        run: ls -l src/main/resources

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: test